### PR TITLE
翻訳修正(zh_tw,zh_cn)

### PR DESCRIPTION
**Pull request by narusekiya**
zh_cnとzh_twのフォント表示が異常になります。
zh↓
zh
ja↓
ja

### CODE REVIEW

**Comment by Mabinogi-delight** [comment]
Simplified Chinese translation for Time Signature is "拍号". I know it is counterintuitive, but that's the way it goes.

**Comment by narusekiya** [comment]
Actually, it’s okay. I didn’t think it had to be changed.
After all, I am used to using Japanese interface.
I just saw it and wanted to fix it.

**Comment by fourthline** [comment]
If it's only translation fix, I can merge it. 
Do other statements need discussion?

> zh_cnとzh_twのフォント表示が異常になります。

> java8 to java17
These options are deleted, so it shows some problems in the zh environment.

**Comment by narusekiya** [comment]
This is just an interface display problem.
Translation corrections you can merge it.
Thank you

**Comment by fourthline** [comment]
image
It may be fixed by specifying the font, but I can not confirm it in my environment.

This pull request cannot be merged if the problem has not been resolved.
Separate it as another issue or hold it until the problem is resolved.

**Comment by narusekiya** [comment]
I try change the font but it didn't work

So I am not sure.

**Comment by narusekiya** [comment]
I found that in the default UIManager, it is not restricted by fonts in zh and en.
But I switched UIManager to Metal and it took effect.
So I am not sure whether to change the UIManager style.
Because this seems to be an Oracle problem.
Unless you want to add code to constrain it.

**Pull request merged**
